name = "smart-llm-router"
main = "smart-llm-router.js"
compatibility_date = "2026-08-27"

[vars]
ACCOUNT_ID = "ad9d77d8f16147c01ff26b56d41cb5a9"
GATEWAY_ID = "4-21-24-gateway"

[ai]
binding = "AI"

[[worker_loaders]]
binding = "LOADER"

[[kv_namespaces]]
binding = "ROUTER_KV"
id = "dbedcc63db6040bca9112a8625531a39"
