name = "assistedly-slot4"
main = ".open-next/worker.js"
account_id = "ad9d77d8f16147c01ff26b56d41cb5a9"
compatibility_date = "2026-05-24"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

[[d1_databases]]
binding = "assistedly_analytics"
database_name = "assistedly-analytics"
database_id = "fa630e9b-d7e2-4919-ad5b-cc3f9f69da44"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_SITE_URL = "https://assistedly.ai"
NEXT_PUBLIC_POSTHOG_HOST = "https://d.assistedly.ai"
NEXT_PUBLIC_POSTHOG_KEY = "phc_w95LL2CJ592qM2q4Co6WRZtyLo5ZSjdwEViUPJeZhAuA"
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-E65GGHME88"



