'use client'

import TrustCenterPage from "./TrustCenterPage";
import { TRUST_CENTER_PAGES } from "../lib/trustCenterPages";

const FAQ_QUESTIONS = [
  {
    question: "How is Assistedly.ai different from traditional assisted living brokers?",
    answer:
      "We do not take placement commissions. Our AI ranks facilities on quality signals, not referral fees. We are transparent about how we make money and never sell your data without consent.",
  },
  {
    question: "Is my personal information sold to facilities?",
    answer:
      "No. We operate privacy-first. Family contact details are not sold as lead inventory. Any data sharing requires explicit opt-in.",
  },
  {
    question: "How does Assistedly.ai make money?",
    answer:
      "The platform earns revenue through optional premium memberships and guided decision-support packages. We do not sell placements, referral leads, or paid ranking slots to facilities.",
  },
  {
    question: "Does the business model change the recommendations I see?",
    answer:
      "No. Rankings and recommendations are generated by our AI model using public data, inspection reports, and family inputs. Commercial relationships do not influence facility order.",
  },
  {
    question: "How does the AI matching work?",
    answer:
      "Our model aggregates Massachusetts public licensing data, inspection findings, pricing tiers, staffing ratios, and your personalized inputs to generate a ranked shortlist with plain-English explanations.",
  },
  {
    question: "Can AI replace an in-person tour?",
    answer:
      "No. Assistedly.ai is a research accelerator. We help families ask better questions and narrow options faster, but an in-person tour is always recommended before a move.",
  },
];

export default function FAQPageClient() {
  const page = TRUST_CENTER_PAGES["faq"];
  return <TrustCenterPage slug="faq" page={page} />;
}
